apiVersion: v1
kind: Service
metadata:
  name: survey-service
spec:
  selector:
    app: survey-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # The port exposed on the node
  type: NodePort
